default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

cover:
  - platform: template
    covers:
      projector_screen:
        friendly_name: "Projector screen"
        open_cover:
          service: script.open_projector_screen
        close_cover:
          service: script.close_projector_screen
        stop_cover:
          service: script.stop_projector_screen
          
recorder:
  db_url: !secret db_url

binary_sensor:
  - platform: mqtt
    name: "Door Sensor"
    state_topic: "cmnd/KBR-Lamp/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: door

sensor:
  - platform: mqtt
    state_topic: "tele/L-Lamp/SENSOR"
    name: "Lounge Temp"
    unit_of_measurement: "°C"
    value_template: "{{value_json['DHT11'].Temperature }}"
    device_class: temperature
    force_update: true

  - platform: mqtt
    state_topic: "tele/L-Lamp/SENSOR"
    name: "Lounge Humidity"
    value_template: "{{value_json['DHT11'].Humidity }}"
    unit_of_measurement: "%"
    device_class: humidity

light:
  - platform: mqtt
    name: "Bedroom Lamp"
    command_topic: "cmnd/KBR-Lamp/power"
    state_topic: "stat/KBR-Lamp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Julia's Bedroom Lamp"
    command_topic: "cmnd/JBR-Lamp/power"
    state_topic: "stat/JBR-Lamp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    name: "Lounge Lamp"
    command_topic: "cmnd/L-Lamp/power"
    state_topic: "stat/L-Lamp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

camera:
  - platform: ffmpeg
    name: Conservatory Camera
    input: !secret conservatory_camera

  - platform: ffmpeg
    name: Entrance Camera
    input: !secret entrance_camera

  - platform: ffmpeg
    name: Carport Camera
    input: !secret carport_camera

  - platform: ffmpeg
    name: Laundry Camera
    input: !secret laundry_camera

  - platform: ffmpeg
    name: Garden Camera
    input: !secret garden_camera

  - platform: ffmpeg
    name: Pool Camera
    input: !secret pool_camera


media_player:
  - platform: samsungtv_tizen
    host: 192.168.185.200
    name: Lounge TV
    port: 8002
    mac: !secret samsung_tv_mac
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Plex": "3201512006963", "DSTv": "3201804016109"}'
    show_logos: "white-color"

