name: Dynamic README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_readme:
    name: "Update Templates"
    runs-on: ubuntu-latest

    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: Copy Configuration
        run: |

          # Extract the content between the triple backticks
          content=$(awk '/^```$/,/^```$/' README.md | grep -v '^```$')
          # Append the content of configuration.yaml to it
          content="$content\n$(cat configuration.yaml)"
          # Replace the original content in README.md with the modified content
          sed -i "s/^```$.*$```$/```\n$content\n```/" README.md
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: modified-readme
          path: README.md