on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Check if the push contains the configuration.yaml file
      # - name: Check for configuration.yaml
      #   run: |
      #     if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "configuration.yaml"; then
      #       exit 0
      #     else
      #       exit 1
      #     fi
      # Get the contents of the configuration.yaml file
      - name: Get configuration.yaml
        run: |
          config=$(cat configuration.yaml)
      # Insert the contents of the configuration.yaml file into the README.md file
      - name: Update README.md
        run: |
          sed -i -e "/^```$/{N;s/^```\n```$/```\n$config\n```/}" README.md
      # Commit and push the updated README.md file
      - name: Commit and push
        run: |
          git add README.md
          git commit -m "Update README.md with configuration.yaml"
          git push
