name: Copy Configuration

on:
  push:
    branches:
      - master
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Configuration
        run: |
          # Print the current working directory
          
          ls $(pwd)
          # Extract the content between the triple backticks
          content=$(awk '/^```$/,/^```$/' /home/runner/work/hassio-config/hassio-config/README.md | grep -v '^```$')
          # Append the content of configuration.yml to it
          content="$content\n$(cat configuration.yml)"
          # Replace the original content in README.md with the modified content
          sed -i "s/^```$.*$```$/```\n$content\n```/" README.md
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: modified-readme
          path: README.md



