on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      # Check if the push contains the configuration.yaml file
      # - name: Check for configuration.yaml
      #   run: |
      #     if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "configuration.yaml"; then
      #       exit 0
      #     else
      #       exit 1
      #     fi
      # Get the contents of the configuration.yaml file
      - name: Check out rep[ository
        uses: actions/checkout@v2
        
      - name: Get configuration.yaml
        run: |
          config=$(cat configuration.yaml)
          echo $config

      # Insert the contents of the configuration.yaml file into the README.md file
      - name: Update README.md
        run: |
          cat $config | sed '1i```' | sed '$a```' > temp.md
          cat temp.md
          cat README.md
          cat temp.md >> README.md
          cat README.md

      # Commit and push the updated README.md file
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACTION_KEY }}